import { PatientProfile, RhythmType, AIDiagnosis } from './types';

export const DEMO_PATIENTS: PatientProfile[] = [
  {
    id: 'pt-101',
    name: 'Marcus Vance',
    age: 58,
    gender: 'M',
    mrn: 'CRD-89420',
    room: 'ER Bed 04 (Telemetry)',
    chiefComplaint: 'Substernal pressure radiating to left jaw & diaphoresis (onset 45 mins ago)',
    cardiacHistory: ['Hypertension (10 yrs)', 'Hyperlipidemia', 'Heavy smoker (30 pack-years)'],
    medications: ['Atorvastatin 40mg', 'Amlodipine 5mg'],
    initialRhythm: 'STEMI',
  },
  {
    id: 'pt-102',
    name: 'Sarah Jenkins',
    age: 39,
    gender: 'F',
    mrn: 'CRD-71203',
    room: 'Telemetry Ward 3B',
    chiefComplaint: 'Sudden onset fluttering sensations, palpitations, and mild dyspnea at rest',
    cardiacHistory: ['Mitral valve prolapse', 'Prior episodes of supraventricular tachycardia'],
    medications: ['Metoprolol Tartrate 25mg BID', 'Multivitamin'],
    initialRhythm: 'AFIB',
  },
  {
    id: 'pt-103',
    name: 'David Chen',
    age: 49,
    gender: 'M',
    mrn: 'CRD-65491',
    room: 'PACU / Stepdown 12',
    chiefComplaint: 'Post-operative monitoring following elective laparoscopic cholecystectomy',
    cardiacHistory: ['No known prior cardiac disease', 'Normal baseline pre-op ECG'],
    medications: ['Acetaminophen 1g PRN', 'IV Normal Saline'],
    initialRhythm: 'NSR',
  },
  {
    id: 'pt-104',
    name: 'Elena Rostova',
    age: 74,
    gender: 'F',
    mrn: 'CRD-90314',
    room: 'Cardiology Bed 08',
    chiefComplaint: 'Recurrent presyncope, fatigue, lightheadedness upon standing',
    cardiacHistory: ['Sick Sinus Syndrome rule-out', 'Coronary artery disease s/p stent (2018)'],
    medications: ['Aspirin 81mg', 'Lisinopril 10mg'],
    initialRhythm: 'BRADYCARDIA',
  },
];

export const RHYTHM_DIAGNOSES: Record<RhythmType, AIDiagnosis> = {
  NSR: {
    rhythm: 'NSR',
    title: 'Normal Sinus Rhythm',
    category: 'Hemodynamically Stable',
    riskLevel: 'LOW',
    confidence: 99.4,
    arrhythmias: ['None detected'],
    stDeviationMm: 0.05,
    prIntervalMs: 158,
    qrsDurationMs: 88,
    qtcIntervalMs: 412,
    clinicalAction: 'Routine hemodynamic telemetry. No immediate acute intervention required.',
    urgencyProtocol: 'Standard Ward Monitoring Protocol • Maintain telemetry surveillance',
    confidenceBreakdown: {
      NSR: 99.4,
      AFIB: 0.3,
      VTACH: 0.0,
      STEMI: 0.1,
      BRADYCARDIA: 0.1,
      PVC_BIGEMINY: 0.1,
    },
  },
  AFIB: {
    rhythm: 'AFIB',
    title: 'Atrial Fibrillation w/ RVR',
    category: 'Supraventricular Tachyarrhythmia',
    riskLevel: 'MODERATE',
    confidence: 97.8,
    arrhythmias: ['Absence of P-waves', 'Irregularly irregular RR intervals', 'Micro-fibrillatory baseline (f-waves)'],
    stDeviationMm: -0.4,
    prIntervalMs: 0,
    qrsDurationMs: 94,
    qtcIntervalMs: 438,
    clinicalAction: 'Evaluate CHA2DS2-VASc score. Rate control with IV beta-blockers or Diltiazem. Anticoagulation assessment.',
    urgencyProtocol: 'Urgent Medical Attention • Continuous Cardiac Telemetry • Stroke Prevention Protocol',
    confidenceBreakdown: {
      NSR: 0.8,
      AFIB: 97.8,
      VTACH: 0.2,
      STEMI: 0.4,
      BRADYCARDIA: 0.1,
      PVC_BIGEMINY: 0.7,
    },
  },
  VTACH: {
    rhythm: 'VTACH',
    title: 'Monomorphic Ventricular Tachycardia',
    category: 'Malignant Ventricular Arrhythmia',
    riskLevel: 'CRITICAL',
    confidence: 98.9,
    arrhythmias: ['Wide complex tachycardia (QRS > 140ms)', 'AV dissociation', 'Rapid ventricular rate > 160 bpm'],
    stDeviationMm: 0.0,
    prIntervalMs: 0,
    qrsDurationMs: 156,
    qtcIntervalMs: 510,
    clinicalAction: 'IMMEDIATE CODE RESPONSE. Assess pulse. If unstable: Synchronized electrical cardioversion (100J). If pulseless: Immediate CPR & Defibrillation.',
    urgencyProtocol: 'EMERGENCY CODE BLUE ALERT • Crash Cart to Bedside • Notify Cardiology Fellow on Call',
    confidenceBreakdown: {
      NSR: 0.0,
      AFIB: 0.4,
      VTACH: 98.9,
      STEMI: 0.5,
      BRADYCARDIA: 0.0,
      PVC_BIGEMINY: 0.2,
    },
  },
  STEMI: {
    rhythm: 'STEMI',
    title: 'Acute ST-Elevation Myocardial Infarction',
    category: 'Acute Coronary Syndrome (Transmural Ischemia)',
    riskLevel: 'CRITICAL',
    confidence: 99.1,
    arrhythmias: ['Tombstone ST-elevation > 2.5mm', 'Hyperacute symmetrical T-waves', 'Reciprocal depression in inferior leads'],
    stDeviationMm: 3.4,
    prIntervalMs: 165,
    qrsDurationMs: 104,
    qtcIntervalMs: 462,
    clinicalAction: 'ACTIVATE CATH LAB IMMEDIATELY. Goal door-to-balloon time < 90 mins. Administer Aspirin 325mg PO, Heparin bolus, SL Nitroglycerin (if BP permits).',
    urgencyProtocol: 'CODE STEMI ACTIVATED • Immediate Interventional Cardiology Transfer • Dual Antiplatelet Load',
    confidenceBreakdown: {
      NSR: 0.2,
      AFIB: 0.2,
      VTACH: 0.3,
      STEMI: 99.1,
      BRADYCARDIA: 0.0,
      PVC_BIGEMINY: 0.2,
    },
  },
  BRADYCARDIA: {
    rhythm: 'BRADYCARDIA',
    title: 'Sinus Bradycardia w/ First Degree AV Block',
    category: 'Conduction Abnormality',
    riskLevel: 'MODERATE',
    confidence: 96.5,
    arrhythmias: ['Sinus rate < 50 bpm', 'Prolonged PR interval > 210ms', 'Regular rhythm'],
    stDeviationMm: 0.0,
    prIntervalMs: 224,
    qrsDurationMs: 92,
    qtcIntervalMs: 422,
    clinicalAction: 'Evaluate for reversible etiologies (beta-blocker toxicity, electrolyte imbalance, hypothyroidism). If symptomatic, prepare Atropine 1mg IV.',
    urgencyProtocol: 'Caution Telemetry • Keep Transcutaneous Pacing Pads Available at Bedside',
    confidenceBreakdown: {
      NSR: 2.3,
      AFIB: 0.1,
      VTACH: 0.0,
      STEMI: 0.2,
      BRADYCARDIA: 96.5,
      PVC_BIGEMINY: 0.9,
    },
  },
  PVC_BIGEMINY: {
    rhythm: 'PVC_BIGEMINY',
    title: 'Ventricular Bigeminy (Frequent PVCs)',
    category: 'Ectopic Ventricular Irritability',
    riskLevel: 'MODERATE',
    confidence: 95.8,
    arrhythmias: ['Every normal sinus beat followed by premature ventricular complex', 'Compensatory post-extrasystolic pause', 'Discordant T-waves'],
    stDeviationMm: -0.3,
    prIntervalMs: 152,
    qrsDurationMs: 142,
    qtcIntervalMs: 445,
    clinicalAction: 'Check serum Potassium and Magnesium levels. Review recent QT-prolonging drugs. Consider telemetry Holter monitoring.',
    urgencyProtocol: 'Targeted Lab Draw (Stat K+/Mg2+) • Notify Attending if Burden > 15%',
    confidenceBreakdown: {
      NSR: 2.1,
      AFIB: 1.0,
      VTACH: 0.8,
      STEMI: 0.3,
      BRADYCARDIA: 0.0,
      PVC_BIGEMINY: 95.8,
    },
  },
};
